apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  progressDeadlineSeconds: 3600
  replicas: 10
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: aksdemoskasun.azurecr.io/javascript-app:0f1e8872f17298fb9b09e10d740420e0291bdca1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
