apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      serviceAccountName: cicd
      containers:
      - name: sampleapp
        image: aksdemoskasun.azurecr.io/javascript-app:692e2c0b4d9aa155956f2e9315417a2c1d1e1996:9ce7b7312e6dff8a4ed84fc85892fd23299aa01c
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
