apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      serviceAccountName: cicd
      containers:
      - name: sampleapp
        image: aksdemoskasun.azurecr.io/javascript-app:6c0ad828cff7abd60de4a65c5c74a180a242e076
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
