apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      serviceAccountName: cicd
      containers:
      - name: sampleapp
        image: aksdemoskasun.azurecr.io/javascript-app:83296966dee9c6b151e3b396a778bc48dc4bf85c
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
