apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: aksdemoskasun.azurecr.io/javascript-app:febb24f32c3405bfea1ccdd2c32ef860454fe454
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 8080
