name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: aksdemoskasun.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ./app/Dockerfile
        context: ./app
        push: true
        tags: aksdemoskasun.azurecr.io/javascript-app:${{ github.sha }}

    - name: Update manifest
      run: |
        version=$(cat ./manifests/deployment.yml | grep image: | awk '{print $2}' | awk -F: '{print $2}')
        echo $version
        sed -i "s|aksdemoskasun.azurecr.io/javascript-app:$version|aksdemoskasun.azurecr.io/javascript-app:${{ github.sha }}|g" ./manifests/deployment.yml
        cat ./manifests/deployment.yml
    
# Commit and push changes
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Update the deployment image tag
