name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: aksdemoskasun.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ./app/Dockerfile
        context: ./app
        push: true
        tags: aksdemoskasun.azurecr.io/javascript-app:${{ github.sha }}

    - name: Update manifest
      run: |
        sed -i "s|aksdemoskasun.azurecr.io/javascript-app:TAG|aksdemoskasun.azurecr.io/javascript-app:${{ github.sha }}|g" ./manifests/deployment.yml
        cat ./manifests/deployment.yml
